<!doctype html>
<html lang="id">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width,initial-scale=1" />
    <title>Praktikum - EduLab</title>

    <!-- Fonts & shared stylesheet to match other pages -->
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@400;700&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="./assets/praktikum.css">
    <link rel="shortcut icon" href="./assets/images/Logo.png" type="image/x-icon">

</head>

<body>
    <div class="loader">
        <div class="spinner"></div>
        <p>Loading...</p>
    </div>
    <div class="app">
        <aside class="panel left">
            <h3 style="margin:0 0 12px 0">🧪 Palet Alat & Bahan</h3>
            <div class="tools" id="tools">
                <!-- tools will be generated by JS -->
            </div>
            <div style="margin-top:8px; font-size:13px; color:var(--muted); line-height:1.4">
                <strong>Petunjuk:</strong> Seret alat/bahan ke beaker untuk bereaksi. Di mobile, tap area lab
                untuk
                quick menu.
            </div>
        </aside>

        <main class="panel workspace">
            <div class="lab-area" id="lab">
                <div class="bench" id="bench">
                    <div class="beaker" id="beaker" aria-label="Beaker">
                        <div class="liquid" id="liquid" style="background:transparent; height:0%">
                        </div>
                        <div class="label">Beaker / Wadah</div>
                    </div>
                    <button class="tray-toggle" id="trayToggle">🧪 Alat & Bahan</button>
                    <div class="tray" id="tray"></div>
                </div>
            </div>
        </main>

        <aside class="panel right">
            <button onclick="window.location.href='./start-praktikum.html'">Kembali </button>
            <button id="selesaiBtn">Selesai</button>
            <div style="display:flex; justify-content:space-between; align-items:center; margin-bottom:12px">
                <h3 style="margin:0">📊 Instrumen</h3>
                <button id="resetBtn2" class="btn" style="padding:6px 12px; font-size:13px">🔄 Reset</button>
            </div>
            <div class="meter">
                <div style="font-size:14px; color:var(--muted)">pH Saat Ini</div>
                <div class="value" id="phValue"></div>
            </div>

            <div class="meter" style="margin-top:10px">
                <div style="font-size:14px; color:var(--muted)">Total Volume Cairan</div>
                <div class="value" id="volumeValue"
                    style="background:linear-gradient(135deg, #60a5fa, #3b82f6); color:white; font-size:24px">
                    0 <span style="font-size:16px; opacity:0.9">ml</span>
                </div>

                <!-- Progress Bar -->
                <div style="margin-top:8px; font-size:12px; color:var(--muted); text-align:center">
                    <span id="volumeBar"
                        style="display:inline-block; width:100%; height:6px; background:rgba(96,165,250,0.2); border-radius:3px; overflow:hidden">
                        <span id="volumeFill"
                            style="display:block; height:100%; width:0%; background:linear-gradient(90deg, #60a5fa, #3b82f6); transition:width 0.3s ease; border-radius:3px"></span>
                    </span>
                </div>

                <div style="margin-top:4px; font-size:11px; color:var(--muted); text-align:center">
                    Kapasitas: <span id="volumePercent">0%</span> / 200ml
                </div>

                <!-- BREAKDOWN PER REAGENT -->
                <div id="volumeBreakdown"
                    style="margin-top:12px; padding-top:10px; border-top:1px dashed rgba(102,126,234,0.2)">
                    <div style="font-size:12px; color:var(--muted); margin-bottom:6px; font-weight:600">📋
                        Komposisi:
                    </div>
                    <div id="breakdownList"
                        style="display:flex; flex-direction:column; gap:4px; max-height:150px; overflow-y:auto">
                        <div style="font-size:11px; color:#94a3b8; font-style:italic; text-align:center; padding:8px">
                            Belum ada cairan
                        </div>
                    </div>
                </div>
            </div>

            <div style="margin-top:10px">
                <div style="display:flex; justify-content:space-between; align-items:center; margin-bottom:8px">
                    <strong>📜 Riwayat Reaksi</strong>
                    <button id="resetBtn" class="btn" style="padding:6px 10px; font-size:13px">Reset</button>
                </div>
                <div class="history" id="history"></div>
            </div>

            <div style="margin-top:10px">
                <strong>📖 pH</strong>
                <div class="legend" style="margin-top:8px">
                    <div style="display:flex; align-items:center; gap:6px">
                        <div class="dot" style="background:#ff6b6b"></div>
                        <div style="color:var(--muted); font-size:12px">Asam Kuat</div>
                    </div>
                    <div style="display:flex; align-items:center; gap:6px">
                        <div class="dot" style="background:#ffb86b"></div>
                        <div style="color:var(--muted); font-size:12px">Asam Lemah</div>
                    </div>
                    <div style="display:flex; align-items:center; gap:6px">
                        <div class="dot" style="background:#60a5fa"></div>
                        <div style="color:var(--muted); font-size:12px">Netral</div>
                    </div>
                    <div style="display:flex; align-items:center; gap:6px">
                        <div class="dot" style="background:#99f6e4"></div>
                        <div style="color:var(--muted); font-size:12px">Basa Lemah</div>
                    </div>
                    <div style="display:flex; align-items:center; gap:6px">
                        <div class="dot" style="background:#6ee7b7"></div>
                        <div style="color:var(--muted); font-size:12px">Basa Kuat</div>
                    </div>
                </div>
            </div>

        </aside>
        <div id="postTestPopup" class="post-test-popup">
            <div class="post-test-content">
                <div class="post-test-header">
                    <h2>📋 Post Test - Evaluasi Praktikum</h2>
                    <button id="closePostTest" class="close-btn">✕</button>
                </div>

                <div class="post-test-body" id="postTestBody">
                    <div class="test-intro">
                        <p style="margin-bottom: 16px; color: var(--text-muted); line-height: 1.6;">
                            Selamat! Anda telah menyelesaikan praktikum virtual. Berikut adalah 5 soal analisis
                            untuk menguji pemahaman Anda tentang konsep asam-basa.
                        </p>
                    </div>

                    <!-- Soal 1 -->
                    <div class="question-card">
                        <div class="question-header">
                            <span class="question-number">Soal 1</span>
                            <span class="question-tag">Air Sumur dan Rasa Asam</span>
                        </div>
                        <div class="question-context">
                            Di sebuah desa pesisir, warga menyadari bahwa air sumur mereka terasa agak asam setelah
                            hujan deras. Seorang siswa ingin mengetahui penyebabnya. Ia mengukur pH air sumur dan
                            mendapatkan nilai <strong>pH = 5,5</strong>.
                        </div>
                        <div class="question-text">
                            <p><strong>Pertanyaan:</strong></p>
                            <ol>
                                <li>Berdasarkan hasil tersebut, termasuk jenis apakah air sumur itu (asam, basa,
                                    atau netral)?</li>
                                <li>Analisislah mengapa air sumur bisa menjadi asam setelah hujan deras! Jelaskan
                                    dengan mengaitkan dengan konsep asam-basa dan lingkungan sekitar.</li>
                            </ol>
                        </div>
                    </div>

                    <!-- Soal 2 -->
                    <div class="question-card">
                        <div class="question-header">
                            <span class="question-number">Soal 2</span>
                            <span class="question-tag">Abu Dapur dan Tanah</span>
                        </div>
                        <div class="question-context">
                            Di desa pegunungan, banyak warga masih menggunakan kayu bakar untuk memasak. Setelah
                            memasak, sisa abu dapur sering digunakan untuk menetralisir keasaman tanah di kebun.
                        </div>
                        <div class="question-text">
                            <p><strong>Pertanyaan:</strong></p>
                            <ol>
                                <li>Jelaskan mengapa abu dapur bisa menetralkan tanah yang asam!</li>
                                <li>Analisis jenis zat kimia apa yang kemungkinan terkandung dalam abu dapur
                                    sehingga dapat bersifat basa.</li>
                            </ol>
                        </div>
                    </div>

                    <!-- Soal 3 -->
                    <div class="question-card">
                        <div class="question-header">
                            <span class="question-number">Soal 3</span>
                            <span class="question-tag">Fermentasi dan Keasaman</span>
                        </div>
                        <div class="question-context">
                            Penduduk di sebuah desa suka membuat tape singkong dan tempe secara tradisional. Dalam
                            prosesnya, makanan menjadi lebih asam seiring waktu fermentasi.
                        </div>
                        <div class="question-text">
                            <p><strong>Pertanyaan:</strong></p>
                            <ol>
                                <li>Jelaskan apa yang menyebabkan makanan hasil fermentasi menjadi asam!</li>
                                <li>Bagaimana pH bahan makanan berubah selama fermentasi? Jelaskan alasannya
                                    berdasarkan konsep asam-basa.</li>
                            </ol>
                        </div>
                    </div>

                    <!-- Soal 4 -->
                    <div class="question-card">
                        <div class="question-header">
                            <span class="question-number">Soal 4</span>
                            <span class="question-tag">Jeruk Nipis dan Sabun Cuci</span>
                        </div>
                        <div class="question-context">
                            Seorang ibu di desa mencuci piring menggunakan campuran air, sabun cuci, dan sedikit
                            perasan jeruk nipis agar lebih bersih.
                        </div>
                        <div class="question-text">
                            <p><strong>Pertanyaan:</strong></p>
                            <ol>
                                <li>Berdasarkan sifat kimianya, sabun termasuk zat asam atau basa?</li>
                                <li>Analisislah mengapa penambahan jeruk nipis (zat asam) dapat membantu
                                    membersihkan lemak lebih baik saat mencuci.</li>
                            </ol>
                        </div>
                    </div>

                    <!-- Soal 5 -->
                    <div class="question-card">
                        <div class="question-header">
                            <span class="question-number">Soal 5</span>
                            <span class="question-tag">Uji Sederhana di Rumah</span>
                        </div>
                        <div class="question-context">
                            Siswa ingin mengetahui zat apa saja di rumahnya yang bersifat asam atau basa. Ia
                            menggunakan air rebusan bunga kembang sepatu (indikator alami) untuk mengujinya. Warna
                            indikator berubah menjadi <strong style="color: #ef4444;">merah</strong> saat dicampur
                            dengan cuka, dan <strong style="color: #10b981;">hijau kebiruan</strong> saat dicampur
                            dengan abu dapur.
                        </div>
                        <div class="question-text">
                            <p><strong>Pertanyaan:</strong></p>
                            <ol>
                                <li>Berdasarkan hasil uji tersebut, klasifikasikan sifat asam atau basa dari kedua
                                    bahan itu.</li>
                                <li>Analisis bagaimana indikator alami bekerja dalam menentukan sifat asam-basa
                                    suatu zat.</li>
                            </ol>
                        </div>
                    </div>
                </div>

                <div class="post-test-footer">
                    <button id="closePostTestBtn" class="btn close-test-btn">
                        ✓ Selesai Membaca
                    </button>
                </div>
            </div>
        </div>
    </div>

    <script src="./assets/praktikum.js"></script>
</body>

</html>